sudo: false
cache:
  bundler: true
  directories:
  - cache/
notifications:
  email: false
language: c
compiler: gcc
env:
  global:
  - PACKAGE=mpu6050
  - USER=frainzy1477
  - REPO=test
  #- secure: "dNTl6qLicvw659/aZlFqbUg9mBQch6iMyMBWmywzRSOxM/CkmDqBqwt+j2Acx5UwqbarOtmsQytsl1r5XgexSjzgt/+diEp2XRoHtDUN6kCEJkaGoZ9oalVFjdsew+lKJPaGbp+pixAaLmpwE26EpVaWdIvh2rp7m0Y3cA6dKD+PRQMJz1MzbJ6/mT1anwulj7hvMxWoHI54PLaoQZQWAJOz+lrUCxX8+4+bSXafmzQOhNwGSESFXket5Zm5W1+F02auIszWt8vr0iZuS8gh5xD+sRKvLAkYUT79xt5bmk7CEZsxyRxg/OdzEa4JLjkOhCqjJQXc9yA1qamBh62msV5dhtEvQKuaXp466x8QAeLZ3kNLXTvntgdai/veAq5vTcz9Vfr4vCYF8YpsISo7CFFzbSldwfcCl8CBmliWpfCUUJoE5HvW22+EyFu8laOZ68ZfAAzHxRX1Qu2/FjRfO7chSEQ/wZC9WhwFMEN7KH6fE26LcenTSVHim2AD2M08D1D778tozSVURuhvMH60poaC6sqJgoK4ZkwFg9fUkLWk/fuI5bEMXoQozXoGvj2jA6RcZVs0z+Hl/Vwi5kHS1743H5FOxxUnW2Ohic1pTe6dttAOI7uvhuVtmXImrBD6w9xOGNrZxXQlhWLj2Y7oFGhC/cVDEkyJIxQzw9Onkr0="
    # Go to GitHub.com -> Settings -> Applications -> Personal Access Tokens 
    # —> Create new token, and copy it to your clipboard
    # travis encrypt GH_Token=123459... -r username/reponame
    # Paste here
  - secure: "7UkuOZBdnRNUEy5r1QxyzoqekuFxmNdEjNHrFj1uJd04Wlx3WGKtGuik62hFgVCJJPr3lAxEm+nJNaSwpDIEamW7CnWgRW/tErmREruli4JesDZZ4MsrtRBOmbSeX3ComvAOqW6b1hEBau9lYit99TB6AOLBt2v3pdtH5xY93CaruBJG6V/KfUjd+S4G6VOy83+TmCUD0Tm1JOtU2YzKexejg0mZWZm4R/VgJFhCC6TrRMLoS9Ts/YHuOX78CzuKzprRJ/aYmb+XVF3I3mOfSVTqwFXM5KjzRBS2Kr1StHbzBit4fT2IoUilA9/AkWSachP2pYCOFBJHqCH84/8Emr8dX0byPCA91u9I2dNzsAUfqNVCjYiykpDS74L5mPyKF3WmSfABkFTXJfMCb2P5A8khiE925TTAj+J2kkm/ZkA5GsqQ8gf5WROdIOoRVSmm6/dNebPkvzn5OZJ1ThhpQPmM80zuLAYA0vZd1ph8q3v79mkT0xXP6VzOGFXPfsZHY0QlQ2wnXoqxNB3n9q64MiQ159b3t07onU8Hp2OJDhE6YR1KLeTxzWWNk6vhVwI4ZlPWQ5WkZFS3VQciQnm9+xgxFNOmIOc5UzyP9MK6TEWKjZeQNQ7SQqt/0f/ffG2di2MQBqBOY/ZGQPBFDgsB3F/F11BbP12q3FrOr3sJtEE="
    # Go to GitHub.com -> Settings -> Applications -> Personal Access Tokens 
    # —> Create new token, and copy it to your clipboard
    # travis encrypt TOKEN=123459... -r username/reponame
    # Paste here
  matrix:
  - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/ar71xx/generic/OpenWrt-SDK-15.05-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/ramips/mt7620/OpenWrt-SDK-15.05-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/brcm63xx/generic/OpenWrt-SDK-15.05-brcm63xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/ramips/mt7621/OpenWrt-SDK-15.05-ramips-mt7621_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/ramips/mt7628/OpenWrt-SDK-15.05-ramips-mt7628_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/bcm53xx/generic/OpenWrt-SDK-15.05-bcm53xx_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64.tar.bz2
  - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/brcm47xx/generic/OpenWrt-SDK-15.05-brcm47xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/x86/generic/OpenWrt-SDK-15.05-x86-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
install:
- mkdir -p $TRAVIS_BUILD_DIR/local ; cd $TRAVIS_BUILD_DIR/local
- wget "http://us.archive.ubuntu.com/ubuntu/pool/main/c/ccache/ccache_3.1.6-1_amd64.deb"
- dpkg -x *.deb .
- mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
- export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
- file $FILE
- tar xjf $FILE
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- mkdir package/$PACKAGE
- ln -s $TRAVIS_BUILD_DIR/Makefile package/$PACKAGE/
- ln -s $TRAVIS_BUILD_DIR/src package/$PACKAGE/
script:
- export PATH=$TRAVIS_BUILD_DIR/local/usr/bin:$PATH
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- "./scripts/feeds update packages >/dev/null"
- make V=s
- find $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*/bin/
#- find $TRAVIS_BUILD_DIR -name '*libstdc*' #查找libstdcpp
- find . -name *.ipk -exec cp {} $TRAVIS_BUILD_DIR \;
- cd $TRAVIS_BUILD_DIR/
- chmod a+x $TRAVIS_BUILD_DIR/deploy.sh
after_success: "$TRAVIS_BUILD_DIR/deploy.sh"
before_deploy: git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: "7UkuOZBdnRNUEy5r1QxyzoqekuFxmNdEjNHrFj1uJd04Wlx3WGKtGuik62hFgVCJJPr3lAxEm+nJNaSwpDIEamW7CnWgRW/tErmREruli4JesDZZ4MsrtRBOmbSeX3ComvAOqW6b1hEBau9lYit99TB6AOLBt2v3pdtH5xY93CaruBJG6V/KfUjd+S4G6VOy83+TmCUD0Tm1JOtU2YzKexejg0mZWZm4R/VgJFhCC6TrRMLoS9Ts/YHuOX78CzuKzprRJ/aYmb+XVF3I3mOfSVTqwFXM5KjzRBS2Kr1StHbzBit4fT2IoUilA9/AkWSachP2pYCOFBJHqCH84/8Emr8dX0byPCA91u9I2dNzsAUfqNVCjYiykpDS74L5mPyKF3WmSfABkFTXJfMCb2P5A8khiE925TTAj+J2kkm/ZkA5GsqQ8gf5WROdIOoRVSmm6/dNebPkvzn5OZJ1ThhpQPmM80zuLAYA0vZd1ph8q3v79mkT0xXP6VzOGFXPfsZHY0QlQ2wnXoqxNB3n9q64MiQ159b3t07onU8Hp2OJDhE6YR1KLeTxzWWNk6vhVwI4ZlPWQ5WkZFS3VQciQnm9+xgxFNOmIOc5UzyP9MK6TEWKjZeQNQ7SQqt/0f/ffG2di2MQBqBOY/ZGQPBFDgsB3F/F11BbP12q3FrOr3sJtEE="
      # Go to GitHub.com -> Settings -> Applications -> Personal Access Tokens 
      # —> Create new token, and copy it to your clipboard
      # travis-encrypt -r username/reponame 123459...
      # Paste here
  skip_cleanup: true
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/*.ipk"
  on:
    tags: true
    all_branches: true
